# ----------------------------------------------------- 
# Monitor Setup
# name: "Default"
# ----------------------------------------------------- 

# 0x0 is in the top left corner of the primary monitor.
# We need to apply the scale factor to the resolution for the position.

monitorv2 {
  output = eDP-1
  mode = preferred
  position = 0x0
  scale = 1.33
}

monitorv2 {
  output = HDMI-A-1
  mode = preferred
  position = 1920x0
  scale = 1
  supports_hdr = 1
}

monitorv2 {
  output = DP-3
  mode = preferred
  position = 2500x-1080
  scale = 1
}

monitorv2 {
  output = DP-1
  mode = preferred
  position = 2500x-1080
  scale = 1
}

xwayland {
  force_zero_scaling = true
}